package HistoryServer;


/**
* HistoryServer/HistoryServerCommunicationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerClient.idl
* Montag, 29. April 2019 um 12:06:01 Mitteleuropäische Sommerzeit
*/

public abstract class HistoryServerCommunicationPOA extends org.omg.PortableServer.Servant
 implements HistoryServer.HistoryServerCommunicationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getHistory", new java.lang.Integer (0));
    _methods.put ("MessageToHistory", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HistoryServer/HistoryServerCommunication/getHistory
       {
         HistoryServer.Message $result[] = null;
         $result = this.getHistory ();
         out = $rh.createReply();
         HistoryServer.HistoryHelper.write (out, $result);
         break;
       }

       case 1:  // HistoryServer/HistoryServerCommunication/MessageToHistory
       {
         String nickname = in.read_string ();
         String message = in.read_string ();
         this.MessageToHistory (nickname, message);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HistoryServer/HistoryServerCommunication:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public HistoryServerCommunication _this() 
  {
    return HistoryServerCommunicationHelper.narrow(
    super._this_object());
  }

  public HistoryServerCommunication _this(org.omg.CORBA.ORB orb) 
  {
    return HistoryServerCommunicationHelper.narrow(
    super._this_object(orb));
  }


} // class HistoryServerCommunicationPOA
