package HistoryServer;


/**
* HistoryServer/HistoryServerCommunication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerClient.idl
* Montag, 29. April 2019 um 12:06:01 Mitteleuropäische Sommerzeit
*/

public interface HistoryServerCommunication extends HistoryServerCommunicationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HistoryServerCommunication
