package HistoryServer;


/**
* HistoryServer/HistoryServerCommunicationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerClient.idl
* Montag, 29. April 2019 um 12:06:01 Mitteleuropäische Sommerzeit
*/

public interface HistoryServerCommunicationOperations 
{
  HistoryServer.Message[] getHistory ();
  void MessageToHistory (String nickname, String message);
} // interface HistoryServerCommunicationOperations
