package HistoryServer;

/**
* HistoryServer/MessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerClient.idl
* Montag, 29. April 2019 um 12:06:01 Mitteleuropäische Sommerzeit
*/

public final class MessageHolder implements org.omg.CORBA.portable.Streamable
{
  public HistoryServer.Message value = null;

  public MessageHolder ()
  {
  }

  public MessageHolder (HistoryServer.Message initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HistoryServer.MessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HistoryServer.MessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HistoryServer.MessageHelper.type ();
  }

}
