package HistoryServer;


/**
* HistoryServer/Message.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerClient.idl
* Montag, 29. April 2019 um 12:06:01 Mitteleuropäische Sommerzeit
*/

public final class Message implements org.omg.CORBA.portable.IDLEntity
{
  public String nickname = null;
  public String content = null;

  public Message ()
  {
  } // ctor

  public Message (String _nickname, String _content)
  {
    nickname = _nickname;
    content = _content;
  } // ctor

} // class Message
