package ServerClient;


/*
* ServerClient/ClientServerCommunicationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerClient.idl
* Montag, 29. April 2019 um 12:06:01 Mitteleurop�ische Sommerzeit
*/

public interface ClientServerCommunicationOperations 
{
  void sendMessage (String nickname, String message);
  void register (String nickname, ServerClient.Receiver receive);
  void unregister (String nickname);
} // interface ClientServerCommunicationOperations
