package ServerClient;


/**
* ServerClient/ClientServerCommunicationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerClient.idl
* Montag, 29. April 2019 um 12:06:01 Mitteleuropäische Sommerzeit
*/

public abstract class ClientServerCommunicationPOA extends org.omg.PortableServer.Servant
 implements ServerClient.ClientServerCommunicationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendMessage", new java.lang.Integer (0));
    _methods.put ("register", new java.lang.Integer (1));
    _methods.put ("unregister", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ServerClient/ClientServerCommunication/sendMessage
       {
         String nickname = in.read_string ();
         String message = in.read_string ();
         this.sendMessage (nickname, message);
         out = $rh.createReply();
         break;
       }

       case 1:  // ServerClient/ClientServerCommunication/register
       {
         String nickname = in.read_string ();
         ServerClient.Receiver receive = ServerClient.ReceiverHelper.read (in);
         this.register (nickname, receive);
         out = $rh.createReply();
         break;
       }

       case 2:  // ServerClient/ClientServerCommunication/unregister
       {
         String nickname = in.read_string ();
         this.unregister (nickname);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerClient/ClientServerCommunication:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientServerCommunication _this() 
  {
    return ClientServerCommunicationHelper.narrow(
    super._this_object());
  }

  public ClientServerCommunication _this(org.omg.CORBA.ORB orb) 
  {
    return ClientServerCommunicationHelper.narrow(
    super._this_object(orb));
  }


} // class ClientServerCommunicationPOA
