package ServerClient;


/*
* ServerClient/HistoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerClient.idl
* Montag, 29. April 2019 um 12:06:01 Mitteleurop�ische Sommerzeit
*/

public final class HistoryHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerClient.Message value[] = null;

  public HistoryHolder ()
  {
  }

  public HistoryHolder (ServerClient.Message[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerClient.HistoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerClient.HistoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerClient.HistoryHelper.type ();
  }

}
