package ServerClient;

/**
* ServerClient/ReceiverHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerClient.idl
* Montag, 29. April 2019 um 12:06:01 Mitteleuropäische Sommerzeit
*/

public final class ReceiverHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerClient.Receiver value = null;

  public ReceiverHolder ()
  {
  }

  public ReceiverHolder (ServerClient.Receiver initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerClient.ReceiverHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerClient.ReceiverHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerClient.ReceiverHelper.type ();
  }

}
