package ServerClient;


/*
* ServerClient/ReceiverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerClient.idl
* Montag, 29. April 2019 um 12:06:01 Mitteleurop�ische Sommerzeit
*/

public interface ReceiverOperations 
{
  void newMessage (String nickname, String message);
  void newUser (String nickname);
  void removeUser (String nickname);
  void newHistory (ServerClient.Message[] history);
} // interface ReceiverOperations
