package ChatApp;


/*
* ChatApp/ChatHistoryMethodsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:26:06 Mitteleurop�ische Sommerzeit
*/

public interface ChatHistoryMethodsOperations 
{
  ChatApp.HistoryMessage[] getHistory ();
  void addMessage (String clientName, String message);
} // interface ChatHistoryMethodsOperations
