package ChatApp;


/**
* ChatApp/ChatClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:26:06 Mitteleuropäische Sommerzeit
*/

public interface ChatClient extends ChatClientOperations, ChatApp.MessageReceiver, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatClient
