package ChatApp;

/**
* ChatApp/ChatServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:26:06 Mitteleuropäische Sommerzeit
*/

public final class ChatServerHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatApp.ChatServer value = null;

  public ChatServerHolder ()
  {
  }

  public ChatServerHolder (ChatApp.ChatServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatApp.ChatServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatApp.ChatServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatApp.ChatServerHelper.type ();
  }

}
