package ChatApp;


/**
* ChatApp/HistoryMessage.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:26:05 Mitteleuropäische Sommerzeit
*/

public final class HistoryMessage implements org.omg.CORBA.portable.IDLEntity
{
  public String clientName = null;
  public String message = null;

  public HistoryMessage ()
  {
  } // ctor

  public HistoryMessage (String _clientName, String _message)
  {
    clientName = _clientName;
    message = _message;
  } // ctor

} // class HistoryMessage
