package ChatApp;


/**
* ChatApp/MessageReceiverPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:26:06 Mitteleuropäische Sommerzeit
*/


//client and server interface
public abstract class MessageReceiverPOA extends org.omg.PortableServer.Servant
 implements ChatApp.MessageReceiverOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("receiveMessage", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ChatApp/MessageReceiver/receiveMessage
       {
         String clientName = in.read_string ();
         String chatMessage = in.read_string ();
         this.receiveMessage (clientName, chatMessage);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ChatApp/MessageReceiver:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MessageReceiver _this() 
  {
    return MessageReceiverHelper.narrow(
    super._this_object());
  }

  public MessageReceiver _this(org.omg.CORBA.ORB orb) 
  {
    return MessageReceiverHelper.narrow(
    super._this_object(orb));
  }


} // class MessageReceiverPOA
