package ChatApp;


/*
* ChatApp/ChatHistoryMethodsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Mittwoch, 8. Mai 2019 um 13:11:20 Mitteleurop�ische Sommerzeit
*/

public interface ChatHistoryMethodsOperations 
{
  ChatApp.HistoryMessage[] getHistory ();
  void addMessage (String clientName, String message);
} // interface ChatHistoryMethodsOperations
