package ChatApp;


/*
* ChatApp/ChatServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Mittwoch, 8. Mai 2019 um 13:11:20 Mitteleurop�ische Sommerzeit
*/

public interface ChatServerOperations  extends ChatApp.MessageReceiverOperations
{
  boolean login (String clientName, ChatApp.ChatClient chatClient);
  boolean logout (String clientName);
} // interface ChatServerOperations
