package ChatApp;


/*
* ChatApp/MessageReceiverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Mittwoch, 8. Mai 2019 um 13:11:20 Mitteleurop�ische Sommerzeit
*/


//client and server interface
public interface MessageReceiverOperations 
{
  void receiveMessage (String clientName, String chatMessage);
} // interface MessageReceiverOperations
