package ChatApp;


/*
* ChatApp/MessageReceiver.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Mittwoch, 8. Mai 2019 um 13:11:20 Mitteleurop�ische Sommerzeit
*/


//client and server interface
public interface MessageReceiver extends MessageReceiverOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MessageReceiver
