package ChatApp;


/**
* ChatApp/ChatHistoryMethodsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:27:18 Mitteleuropäische Sommerzeit
*/

public abstract class ChatHistoryMethodsPOA extends org.omg.PortableServer.Servant
 implements ChatApp.ChatHistoryMethodsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getHistory", new java.lang.Integer (0));
    _methods.put ("addMessage", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ChatApp/ChatHistoryMethods/getHistory
       {
         ChatApp.HistoryMessage $result[] = null;
         $result = this.getHistory ();
         out = $rh.createReply();
         ChatApp.messageHistoryHelper.write (out, $result);
         break;
       }

       case 1:  // ChatApp/ChatHistoryMethods/addMessage
       {
         String clientName = in.read_string ();
         String message = in.read_string ();
         this.addMessage (clientName, message);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ChatApp/ChatHistoryMethods:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ChatHistoryMethods _this() 
  {
    return ChatHistoryMethodsHelper.narrow(
    super._this_object());
  }

  public ChatHistoryMethods _this(org.omg.CORBA.ORB orb) 
  {
    return ChatHistoryMethodsHelper.narrow(
    super._this_object(orb));
  }


} // class ChatHistoryMethodsPOA
