package ChatApp;


/**
* ChatApp/ChatHistoryMethods.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:27:18 Mitteleuropäische Sommerzeit
*/

public interface ChatHistoryMethods extends ChatHistoryMethodsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatHistoryMethods
