package ChatApp;

/**
* ChatApp/ChatClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:27:18 Mitteleuropäische Sommerzeit
*/

public final class ChatClientHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatApp.ChatClient value = null;

  public ChatClientHolder ()
  {
  }

  public ChatClientHolder (ChatApp.ChatClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatApp.ChatClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatApp.ChatClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatApp.ChatClientHelper.type ();
  }

}
