package ChatApp;


/**
* ChatApp/MessageReceiverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:27:18 Mitteleuropäische Sommerzeit
*/


//client and server interface
public interface MessageReceiverOperations 
{
  void receiveMessage (String clientName, String chatMessage);
} // interface MessageReceiverOperations
