package ChatApp;


/**
* ChatApp/MessageReceiverHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:27:18 Mitteleuropäische Sommerzeit
*/


//client and server interface
abstract public class MessageReceiverHelper
{
  private static String  _id = "IDL:ChatApp/MessageReceiver:1.0";

  public static void insert (org.omg.CORBA.Any a, ChatApp.MessageReceiver that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ChatApp.MessageReceiver extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ChatApp.MessageReceiverHelper.id (), "MessageReceiver");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ChatApp.MessageReceiver read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MessageReceiverStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ChatApp.MessageReceiver value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ChatApp.MessageReceiver narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ChatApp.MessageReceiver)
      return (ChatApp.MessageReceiver)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ChatApp._MessageReceiverStub stub = new ChatApp._MessageReceiverStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ChatApp.MessageReceiver unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ChatApp.MessageReceiver)
      return (ChatApp.MessageReceiver)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ChatApp._MessageReceiverStub stub = new ChatApp._MessageReceiverStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
