package ChatApp;


/**
* ChatApp/messageHistoryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:27:17 Mitteleuropäische Sommerzeit
*/

abstract public class messageHistoryHelper
{
  private static String  _id = "IDL:ChatApp/messageHistory:1.0";

  public static void insert (org.omg.CORBA.Any a, ChatApp.HistoryMessage[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ChatApp.HistoryMessage[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ChatApp.HistoryMessageHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ChatApp.messageHistoryHelper.id (), "messageHistory", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ChatApp.HistoryMessage[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ChatApp.HistoryMessage value[] = null;
    int _len0 = istream.read_long ();
    value = new ChatApp.HistoryMessage[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ChatApp.HistoryMessageHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ChatApp.HistoryMessage[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ChatApp.HistoryMessageHelper.write (ostream, value[_i0]);
  }

}
