package ChatApp;


/**
* ChatApp/ChatClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:27:00 Mitteleuropäische Sommerzeit
*/

public interface ChatClientOperations  extends ChatApp.MessageReceiverOperations
{
  void receiveLoginMessage (String clientName);
  void receiveLogoutMessage (String clientName);
} // interface ChatClientOperations
