package ChatApp;

/**
* ChatApp/ChatHistoryMethodsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatApp.idl
* Samstag, 18. Mai 2019 um 15:27:00 Mitteleuropäische Sommerzeit
*/

public final class ChatHistoryMethodsHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatApp.ChatHistoryMethods value = null;

  public ChatHistoryMethodsHolder ()
  {
  }

  public ChatHistoryMethodsHolder (ChatApp.ChatHistoryMethods initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatApp.ChatHistoryMethodsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatApp.ChatHistoryMethodsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatApp.ChatHistoryMethodsHelper.type ();
  }

}
